### ISSUE TITLE
CTFd访问500错误

### ISSUE THREAD

**Issue by mitan9596** [glzjin/CTFd-Whale#11]
在安装插件后，访问CTFd会频繁的500，js什么的经常调用不了
日志查看了一遍，没发现什么问题，最后查看了uwsgi.log，看到以下信息，不知道是否相关
> Traceback (most recent call last):
  File "wsgi.py", line 11, in <module>
    app = create_app()
  File "./CTFd/__init__.py", line 281, in create_app
    init_plugins(app)
  File "./CTFd/plugins/__init__.py", line 196, in init_plugins
    module.load(app)
  File "./CTFd/plugins/ctfd-whale/__init__.py", line 216, in load
    redis_util = RedisUtils(app=app)
  File "./CTFd/plugins/ctfd-whale/redis_utils.py", line 9, in __init__
    self.redis_client = FlaskRedis(app)
  File "/opt/pyenv/versions/3.7.5/envs/ctfdenv/lib/python3.7/site-packages/flask_redis/client.py", line 16, in __init__
    self.init_app(app)
  File "/opt/pyenv/versions/3.7.5/envs/ctfdenv/lib/python3.7/site-packages/flask_redis/client.py", line 38, in init_app
    redis_url, **self.provider_kwargs
  File "/opt/pyenv/versions/3.7.5/envs/ctfdenv/lib/python3.7/site-packages/redis/client.py", line 638, in from_url
    connection_pool = ConnectionPool.from_url(url, db=db, **kwargs)
  File "/opt/pyenv/versions/3.7.5/envs/ctfdenv/lib/python3.7/site-packages/redis/connection.py", line 999, in from_url
    'schemes (%s)' % valid_schemes)
ValueError: Redis URL must specify one of the followingschemes (redis://, rediss://, unix://)

请问这个该怎么解决

**Comment by frankli0324** [comment]
![image](https://user-images.githubusercontent.com/20221896/84917172-90baf580-b0f1-11ea-8a12-9e2d53b5d0b5.png)
请在此处填写docker api的访问url。一般来说是unix:///var/run/docker.sock
如果你的CTFd运行在docker里，你需要将主机的/var/run/docker.sock文件映射到容器内

**Comment by mitan9596** [comment]
@frankli0324 docker api 这里我使用tcp://192.168.66.12:2375，这个不可以吗？必须本机上的吗？

**Comment by frankli0324** [comment]
远程可以。。防火墙？

**Comment by mitan9596** [comment]
我用nginx-uwsgi部署的

**Comment by frankli0324** [comment]
那你可能需要再部署一份redis emmmm
docker单独不需要，但是whale需要

**Comment by mitan9596** [comment]
@frankli0324 明白了，谢谢

**Comment by frankli0324** [comment]
没关系 不谢（

**Comment by frankli0324** [comment]
btw，如果单独部署redis，启动CTFd时记得加上`REDIS_URL`环境变量

**Comment by mitan9596** [comment]
好的
