### ISSUE TITLE
deployment guide 部署指南

### ISSUE THREAD

**Issue by frankli0324** [glzjin/CTFd-Whale#19]
新版CTFd(3.0+)部署

https://github.com/frankli0324/CTFd-Whale/blob/master/INSTALL.md
https://github.com/frankli0324/CTFd-Whale/blob/master/INSTALL.zh-cn.md

会及时维护

**Comment by shanzhuer** [comment]
> 新版CTFd(3.0+)部署
> 
> https://github.com/frankli0324/CTFd-Whale/blob/master/INSTALL.md
> https://github.com/frankli0324/CTFd-Whale/blob/master/INSTALL.zh-cn.md
> 
> 会及时维护

Waiting for db: to be ready
db is ready
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
 * Loaded module, <module 'CTFd.plugins.challenges' from '/opt/CTFd/CTFd/plugins/challenges/__init__.py'>
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    app = create_app()
  File "/opt/CTFd/CTFd/__init__.py", line 281, in create_app
    init_plugins(app)
  File "/opt/CTFd/CTFd/plugins/__init__.py", line 195, in init_plugins
    module = importlib.import_module(module, package="CTFd.plugins")
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/CTFd/CTFd/plugins/ctfd-whale/__init__.py", line 7, in <module>
    from flask_apscheduler import APScheduler
ModuleNotFoundError: No module named 'flask_apscheduler'

**Comment by frankli0324** [comment]
fixed
https://github.com/frankli0324/CTFd-Whale/commit/35ebddc40fe47c534731035bbcee12cb06afafea

**Comment by glzjin** [comment]
此分支已不再维护，如需继续使用请参考 https://github.com/frankli0324/ctfd-whale 。
